### ISSUE TITLE
It does not seem like the   storage: "indexeddb" worked

### ISSUE THREAD

**Issue by y25zhao** [atayahmet/storage-based-queue#1]
I have tried adding a worker to a single channel without calling start(). Expect to see some data in my indexedb inspector from chrome but there is nothing. Am I missing anything? Thanks

**Comment by atayahmet** [comment]
Hi @y25zhao 

Just supports `localstorage` and `inmemory` storage types. Old information is left in documentation. You need custom driver for using `indexxeddb` storage. I will fix the docs.

See: [Custom storage driver](https://github.com/atayahmet/storage-based-queue/wiki/Drivers)

**Comment by atayahmet** [comment]
You can use [localforage](https://github.com/localForage/localForage) to create a custom driver for `indexeddb`.

**Comment by y25zhao** [comment]
Just did that and it works like a charm. BTW, your work is very neat! 👍

**Comment by atayahmet** [comment]
Thanks @y25zhao
