### ISSUE TITLE
Don't think channel.on is working as described on Wiki

### ISSUE THREAD

**Issue by y25zhao** [atayahmet/storage-based-queue#3]
I am trying to listen to the after event for tag called 'dummy'. When I do this:
        this.channel.on("[dummy]:after", function() {
            console.log('test test');
        });

It just throws an error. I think there is a bug when determine the event type.

**Comment by atayahmet** [comment]
@y25zhao 

You should use this way:
```javascript
this.channel.on("dummy:after", function() {
  console.log('test test');
});
```

Remove the square brackets.

**Comment by y25zhao** [comment]
Got it. Maybe a good idea to update the wiki page. :) Thanks for the answer.

**Comment by atayahmet** [comment]
I will. Thanks for contributions.
