### ISSUE TITLE
clear should return promise

### ISSUE THREAD

**Issue by y25zhao** [atayahmet/storage-based-queue#4]
https://github.com/atayahmet/storage-based-queue/blob/183b39695a2df63cfd675bef2a6b44735fa7069d/src/channel.js#L203

Hi, I think clear should be returned as a promise. Currently I am trying to listen when clear is completed but I could not.

**Comment by y25zhao** [comment]
Hey I would like to propose a quick fix for this:
In Storage-Capsule.js
  async clear(channel: string): Promise<void> {
    const result = await this.storage.clear(channel);
    return result;
  }

In channel.js do something like this:
  async clear(): Promise<void> {
    const self = this;
    if (!this.name()) {
      return new Promise((resolve) => {
        resolve(false);
      });
    }
    const result = await self.storage.clear(self.name());
    return result;
  }

**Comment by atayahmet** [comment]
Hi @y25zhao 

Fixed.

channel.js:
```javascript
async clear(): Promise<boolean> {
    if (!this.name()) return false;
    await this.storage.clear(this.name());
    return true;
  }
```

See:  [a298b55e6b8](https://github.com/atayahmet/storage-based-queue/commit/a298b55e6b80d006ffcb2476363bdc02b73c015c)

**Comment by y25zhao** [comment]
Thanks @atayahmet  Could you also update package.json to 1.2.3 so we could pick it up the latest version and test it? Thanks a lot for the quick fix.

**Comment by y25zhao** [comment]
Saw the checkin. Works great. Thanks @atayahmet
