### ISSUE TITLE
Is project compatible with UglifyJs?

### ISSUE THREAD

**Issue by y25zhao** [atayahmet/storage-based-queue#5]
Hi
I am currently experiencing some issues with packaging my project using uglifyjs. Seems like this project is throwing some errors when building with uglifyjs:

ERROR in vendor.js from UglifyJs
Unexpected token: name (r) [xxxxxxxx]

Could you help us to make it uglifyjs-compatible?

Thanks

**Comment by atayahmet** [comment]
Hi @y25zhao 

Which file do you add to the project? If you are using the es6 import, it's should not any syntax error. I only used uglifyjs for `dist/` versions.

**Comment by y25zhao** [comment]
@atayahmet We are including the project via npm by including:
    "storage-based-queue": "^1.2.3",
in package.json.
In our webpack.config, we are using UglifyJsPlugin()

It does not work even when I tried import Queue from 'storage-based-queue'.
I am trying to see if manually include project source works or not.

**Comment by atayahmet** [comment]
I used facebook `flowtype` in the project for typings. It's transform to pure javascript with babel plugins. It's really does generate ugly code. That may be problem in your `webpack` process.

**Comment by atayahmet** [comment]
Are you sure this problem experiencing in the my package? I tested at React Native (Metro Bundler) and Ionic (Webpack) environments.

**Comment by y25zhao** [comment]
Looks like if I manually import your source code everything works fine ... But not directly through npm

**Comment by y25zhao** [comment]
@atayahmet Yes. This issue occurs only if I include and link your package.

**Comment by atayahmet** [comment]
@y25zhao ,

assuming you solved this problem. I close for now.

**Comment by y25zhao** [comment]
Yes. I managed to resolve it by including the source code. Not pretty but it worked :)
