### ISSUE TITLE
channel.isStopped is not really stopped when the last running task is still in process

### ISSUE THREAD

**Issue by y25zhao** [atayahmet/storage-based-queue#6]
I noticed that channel.isStooped flag is set to true right after channel.stop() or channel.forceStop() is called. Do we have anything I can use to determine if the channel is fully stopped? Thanks

**Comment by atayahmet** [comment]
@y25zhao 

There is a method that called `channel.status()` that you can use, but it was not working properly. I fixed it. You need update the package.

See changes: [ff631b1](https://github.com/atayahmet/storage-based-queue/commit/ff631b16db3995ddbe3ca59cc9dd1256fca37979)

**Comment by y25zhao** [comment]
Great! Thanks @atayahmet Let me give this a shot today and I will update this ticket if it's working.

**Comment by atayahmet** [comment]
Ping @y25zhao

**Comment by y25zhao** [comment]
Hi @atayahmet  sorry for the late response. I think there is still a bug to status(). When I stop the channel. A work could still be running for a few more seconds for e.g. I was expecting the channel to tell me a work under this channel has not finished yet.

**Comment by y25zhao** [comment]
Just FYI, I am currently working around it by listening :before and :after for every work under each channel. And I created my local var to track the running state of each work. Not ideal but works for now . :)
