### ISSUE TITLE
stop processing newly arrived tasks upon forcestop or stop

### ISSUE THREAD

**Issue by y25zhao** [atayahmet/storage-based-queue#7]
HI @atayahmet 
Could we enforce channel to be completely stopped after stop/forcestop is called? I mean currently if I call stop/forcestop, the channel is like 'paused'. But it gets automatically resumed after another task is added. Is there any quick enhancement we could do to give API an option to completely stop the channel until the next start() is called? 

Thanks for help

**Comment by y25zhao** [comment]
Let me revise my question a little. My current project requires channel to be auto stopped after all its tasks are completed. When new tasks are coming in, it needs to remain stopped until manually calling start function. Is it possible for us to get a quick enhancement fix for this request? Thanks a lot

**Comment by atayahmet** [comment]
Hi @y25zhao 

If all tasks is completed, queue process will stop automatically but listener continue listen of the new tasks. You should use `stop()` or `forceStop()`

Will it work if I trigger an event after all tasks are finished?

For example:

```javascript
channel.on("completed", function() {
  channel.forceStop();
});
```

**Comment by y25zhao** [comment]
That would be great indeed. Could you provide a quick enhancement checkin?
Thanks

**Comment by atayahmet** [comment]
@y25zhao 

Event added. Update the package.

**Comment by y25zhao** [comment]
Thanks a lot for quick check-in. I will pick it up later today. Thanks
